### ISSUE TITLE
Config Locations

### ISSUE THREAD

**Issue by chappy1978** [Desuuuu/DGUS-reloaded-Klipper-config#1]
Why don't you just add these to your own branch of Klipper. It took me a long time to stumble across the config files . 

 Thanks For All the Hard Work.
J

**Comment by Desuuuu** [comment]
A quick glance at the [firmware's README](https://github.com/Desuuuu/klipper) (which should be one of the first thing you do when you come across a project) would have saved you all that time.

I think it's pretty reasonable to have the original configuration files and the ones specific to this fork in a separate location.
