### ISSUE TITLE
Optimized CR-10S Pro printer.cfg

### ISSUE THREAD

**Issue by ReXT3D** [Desuuuu/DGUS-reloaded-Klipper-config#2]
Are you interested in me either submitting a pull request (it would be my first ever on GitHub) or just providing some details on tweaks to the CR-10S Pro `printer.cfg` file?

**Comment by ReXT3D** [comment]
I created a fork and made changes to the CR-10S Pro configuration that reflect my optimizations:

[printer-creality-cr10spro.cfg](https://github.com/ReXT3D/DGUS-reloaded-Klipper-config/blob/master/examples/printer-creality-cr10spro.cfg)

**Comment by Desuuuu** [comment]
Sorry for not coming back to this earlier. I updated the macros and added your configuration file to the repository.

I haven't merged the PR yet, so you can have a look at it: #3.

**Comment by ReXT3D** [comment]
No worries whatsoever.  It all looks good to me.  Also please note that you absolutely do not need to add any credits to me in your other configuration files.
