### ISSUE TITLE
Problems with Ender6 

### ISSUE THREAD

**Issue by botanicz** [Desuuuu/DGUS-reloaded-Klipper-config#4]
Hey , 

i tried to get Klipper working on my ender 6 . Without using touchscreen all went well . 
Now i attempted to use touchscreen and merged desuuuu klipper to my firmware . 
when i try to connect to my printer now i get no connection . 
Can u maybe help me out ? 

![Unbenannt](https://user-images.githubusercontent.com/83694871/117110573-9b708e80-ad86-11eb-93c4-304d061b8efa.JPG)

**Comment by Desuuuu** [comment]
GitHub issues are not the place to ask for help.
