### ISSUE TITLE
Macros no longer working propery

### ISSUE THREAD

**Issue by tonysmartantzoulatos** [Desuuuu/DGUS-reloaded-Klipper-config#5]
Just today and most likely after the latest octoklipper update filament change macros started showing the following.
![image](https://user-images.githubusercontent.com/29582764/118971191-c9092a80-b977-11eb-81cc-851cc1365787.png)
Thank you for your KLIPPER version. It has made my printer properly functional

**Comment by Desuuuu** [comment]
The correct syntax for the command should be `PAUSE_PARK X=20 Y=290 Z=20`.
