### ISSUE TITLE
BLTouch not working

### ISSUE THREAD

**Issue by moddok** [Desuuuu/DGUS-reloaded-Klipper-config#8]
Hi,
i hope this is the right section.
On my CR-10s Pro v2 the BLTouch Probe is not working. I used the bltouch part of your config, but the following happens:

when i startup the printer it sometimes says: // Failed to verify BLTouch probe is raised; retrying.
sometimes not. strange.
as soon i send a BLTOUCH_DEBUG COMMAND=pin_down the probe begins to flash red. sending an BLTOUCH_DEBUG COMMAND=reset stops the flashing.
trying to lower the pin results in the same error.

i got it to work one single time (the debug stuff) but as soon as i wanted to auto home the printer it says !! BLTouch failed to deploy.

do you have ANY idea what the problem could be? the wiring should be fine since the probe was wired by the factory and worked 100% when using marlin 
also it always says open. in between this two commands i pulled down the pin so that the result should be different, right?
12:10:24 $ QUERY_PROBE
12:10:24 // probe: open
12:11:01 $ QUERY_PROBE
12:11:01 // probe: open
and lol, after that right now pin_down, pin_up and self_test are working. but it still only reports open

**Comment by Desuuuu** [comment]
Can you try disabling the pull-up resistor on the sensor pin (i.e. `sensor_pin: PD2`)?

**Comment by moddok** [comment]
> Can you try disabling the pull-up resistor on the sensor pin (i.e. `sensor_pin: PD2`)?

i fixed it. it wasn't a software problem. i had to turn the screw on the top of the probe half a turn clockwise. this changes somehow the internal magnet stuff that is going on. now it works perfect.
