### ISSUE TITLE
CR-10S Pro - BLTouch not working

### ISSUE THREAD

**Issue by danb35** [Desuuuu/DGUS-reloaded-Klipper-config#9]
I'd installed a BLTouch on my CR-10S a couple of years back, and IIRC, had flashed the TM3D pre-built firmware to use it.  Now I'm wanting to use your fork of Klipper.  Klipper itself installs just fine, and @ReXT3D's config is working well generally--except for the BLTouch.  I copied the relevant section from the CR10S Pro v2 config file, so it looks like this:
```
[bltouch]
sensor_pin: ^PD2
control_pin: PB5
stow_on_each_sample: False
probe_with_touch_mode: True
x_offset: -44
y_offset: -2
z_offset: 0
speed: 4.0
samples: 2
sample_retract_dist: 3.0
```
When trying to home in Z, the printer stops immediately and sets Z to 0.  When trying to control the probe from the terminal, I get:
```
Send: BLTOUCH_DEBUG COMMAND=pin_down
Recv: // Sending BLTOUCH_DEBUG COMMAND=pin_down
Recv: ok
[...]
Send: query_probe
Recv: // probe: TRIGGERED
Recv: ok
[...]
Send: BLTOUCH_DEBUG COMMAND=pin_up
Recv: // Sending BLTOUCH_DEBUG COMMAND=pin_up
Recv: ok
[...]
Send: query_probe
Recv: // probe: TRIGGERED
Recv: ok
```
And the pin does move with these commands.

I'm pretty sure the problem is going to be with the pin configuration, and I'd further guess it's the sensor pin.  The probe is wired to the mainboard as shown in the attached picture--the yellow wire (control?) is going to the pin marked D11, and the black/white pair (sensor?) are going to Z-.  But I haven't been able to find a Klipper-style pinout for this board.

![cr10s - 1](https://user-images.githubusercontent.com/12121759/144717244-d1202baf-1652-4c34-89ca-662c752ae310.jpeg)

**Comment by ReXT3D** [comment]
I have not been using the stock motherboard for a long time now, but looking at my original config the stock Z probe plugs into pin PD3 and you are using PD2 in your config.

**Comment by danb35** [comment]
That was it, thanks.
